### ISSUE TITLE
pgsql database issues

### ISSUE THREAD

**Issue by spesicbc** [forceedge01/behat-sql-extension#106]
When you set
_'engine' => 'pgsql',_
library is not working at all. 
The problem is in:
_vendor/genesis/behat-sql-extension/src/Context/DatabaseProviders/mysql.php_
because of
_class pgsql extends mysql_
and uses its
_getPrimaryKeyForTable_
as

`$sql = sprintf(
            '
            SELECT `COLUMN_NAME` AS `COLUMN_NAME`
            FROM `information_schema`.`COLUMNS`
            WHERE (`TABLE_SCHEMA` = "%s")
            AND (`TABLE_NAME` = "%s")
            AND (`COLUMN_KEY` = "PRI")',
            $database,
            $table
        );`

Primary keys in Postgres cannot be obtained like that

**Comment by forceedge01** [comment]
@spesicbc thanks for reporting, a recent change to this syntax is probably the culprit. Will raise a PR for this soon or if you'd like to implement is fine too?

**Comment by spesicbc** [comment]
https://www.google.com/search?client=ubuntu&channel=fs&q=postgresql+find+primary+key+table&ie=utf-8&oe=utf-8

**Comment by forceedge01** [comment]
@spesicbc thanks for the doc I have found the resource but will dig a few of these out to get a consistent version for multiple postgres versions and allow external provider registrations as well.

**Comment by forceedge01** [comment]
@spesicbc Raised this MR https://github.com/forceedge01/behat-sql-extension/pull/107, you may want to pull this branch down and give it a go see if that enables you to use the extension.

As a side not I would advise on using https://github.com/forceedge01/sql-data-mods which is built on top of this extension to provide a more manageable and clean implementation.

**Comment by forceedge01** [comment]
@spesicbc fix released in version 8.5.0. As an extra bonus - i've added a way to register an external database provider which you can read more about here https://github.com/forceedge01/behat-sql-extension#registering-your-own-database-provider-class. Closing this issue but let me know if you experience any issues.
