### ISSUE TITLE
iHaveAnExistingWithWhere now throws errors when no rows are affected.

### ISSUE THREAD

**Issue by jpswade** [forceedge01/behat-sql-extension#39]
Workaround is to wrap your feature context in a try/catch, however throwing an error when something is not affected seems a bit overzealous...?

**Comment by forceedge01** [comment]
Have an existing infers that one is looking for something that already exists, if it doesnt it throws an exception. This behavior has been like this from day 1.

What are you trying to achieve?

What you could do is catch the specific type of exception which is https://github.com/forceedge01/behat-sql-extension/blob/behat/2.5.x/src/Context/Exceptions/NoRowsAffectedException.php

**Comment by jpswade** [comment]
I think this was fixed, I just hadn't done a pull. Hence closed.
