### ISSUE TITLE
iShouldBeOnUrlMatching matching issue

### ISSUE THREAD

**Issue by jpswade** [forceedge01/behat-sql-extension#40]
Current URL "https://adminarea.example.org.uk/manage-my-cause/sign-in/?req=/manage-my-cause/" does not match pattern "https://adminarea.example.org.uk/manage-my-cause/sign-in/?req=/manage-my-cause/"

**Comment by forceedge01** [comment]
Not sure if this belongs in this behat-sql-extension. Closed anyway.

**Comment by jpswade** [comment]
Had already closed it on that basis.
