### ISSUE TITLE
Ability to configure port

### ISSUE THREAD

**Issue by pincher2012** [forceedge01/behat-sql-extension#45]

**Comment by forceedge01** [comment]
Thanks for logging this issue, would you be able to give more information please? Which version of behat are you using and I presume you would like to configure the port for MySQL?

**Comment by pincher2012** [comment]
* Version of extension: `3.1.1`
* Behat: `2.5.*`

I user docker and run postgresql instance with custom port `5433`. I cant configure database port. This ability missed in documentation and [here](https://github.com/forceedge01/behat-sql-extension/blob/3.1.1/src/Context/DBManager.php#L234).

**Comment by forceedge01** [comment]
https://github.com/forceedge01/behat-sql-extension/pull/46

**Comment by forceedge01** [comment]
Change has been merged in to allow port setting. Available in version 3.2.0, Thanks.
