### ISSUE TITLE
Method SQLHandler::requiredTableColumns is not MySQL 8 compatible

### ISSUE THREAD

**Issue by darren-potter** [forceedge01/behat-sql-extension#89]
The method Genesis\SQLExtension\Context\SQLHandler::requiredTableColumns is not MySQL 8 compatible due to a change in casing by MySQL on the table information_schema.columns. The resulting effect is the method returns a single column with a null value, completely breaking the consumer.

I've created a branch which fixes this, but I cannot submit it for approval as I am not a collaborator.

**Comment by forceedge01** [comment]
Hey Darren, good to hear from you and thanks for opening this issue.

I haven't ever tested this with MySQL 8 before and thanks for fixing this. In terms of fixing this issue, could you please create a fork and then create a pull request from that fork? That should work I believe. Happy to approve once PR comes through :)

Happy collaborating!

**Comment by darren-potter** [comment]
Hi Abdul, good to hear from you too.

PR open: https://github.com/forceedge01/behat-sql-extension/pull/90

Let me know if all is good.
